import Head from 'next/head'

export default function Home() {

  function loading(event: any) {
    const button = event.currentTarget
    button.classList.add('loading')
    const text = button.textContent
    button.innerHTML = `
    <i class="ph-circle-notch"></i>
    ${text}
    `
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="app">
        <h1>Teste os botões</h1>
        <p>
          Interaja com os botões e observe a mudança de aparência e de cursores
        </p>

        <div className="buttons">
          <button className="primary" onClick={loading}>
            interaja comigo</button>
          <button className="secondary">interaja comigo</button>
          <button className="tertiary movable">
            <i className="ph-list"></i>
            interaja comigo</button>
        </div>
      </div>
    </>
  )
}
